**Practical - 3**

**Implement
i) Simple and Multiple Linear Regression using Normal
Equation,
ii) Simple and Multiple Linear Regression using Gradient
Descent method without using sklearn.
Note: Use Numpy for Linear Algebra and Pandas to deal with
datasets
Apply it on following Datasets:
Simple Linear Regression:
https://www.kaggle.com/datasets/abhishek14398/salarydataset-simple-linear-regression
Multiple Linear Regression:
https://www.kaggle.com/datasets/nikhil7280/studentperformance-multiple-linear-regression
Students may create (fake) data sets with linear/non-linear
relation using functions like np.random.rand().**

**Batch Gradient Descant, Stochastic Gradient Descant and Mini Batch Gradient Descent**

In [78]:
import numpy as np

**i) Simple Linear Regression using normal equation**

In [79]:
# Reproducible seed
np.random.seed(42)

# Generate synthetic data
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

# Add bias term (intercept column)
X_b = np.c_[np.ones((X.shape[0], 1)), X]  # shape (100,2)

# Normal Equation: theta = (X^T X)^(-1) X^T y
theta_normal = np.linalg.inv(X_b.T @ X_b) @ (X_b.T @ y)

# Compute R^2 score
y_hat = X_b @ theta_normal
mse = np.mean((y - y_hat) ** 2)

print("Normal Equation coefficients:", theta_normal.flatten())

print("MSE:", mse)

Normal Equation coefficients: [4.21509616 2.77011339]
MSE: 0.8065845639670531


**Multiple Linear Regression using normal equation**

In [80]:
# Reproducible results
np.random.seed(42)

# Generate data with 3 features
X = 2 * np.random.rand(100, 3)
y = 4 + 3*X[:, 0] + 3*X[:, 1] + 3*X[:, 2] + np.random.randn(100)

# Add bias (intercept term)
X_b = np.c_[np.ones((X.shape[0], 1)), X]  # shape (100, 4)

# Normal Equation
theta = np.linalg.inv(X_b.T @ X_b) @ (X_b.T @ y)

# Predictions
y_pred = X_b @ theta

mse = np.mean((y - y_pred) ** 2)

print("Coefficients (intercept + 3 features):", theta)
print("MSE:", mse)

Coefficients (intercept + 3 features): [3.73501456 3.13900206 2.9211189  3.28520288]
MSE: 0.9203988206421481


**ii) Simple and Multiple Linear Regression using Gradient Descent method without using sklearn.**

In [81]:
print("Choose which Linear Regression you want to go for:")
print("1. Simple Linear Regression")
print("2. Multiple Linear Regression")

def switch_example(value):
    if value == 1:
        # Simple Linear Regression: y = 4 + 3X + noise
        X = 2 * np.random.rand(100, 1)
        true_theta_simple = np.array([4, 3]).reshape(-1, 1)
        y = 4 + 3 * X + np.random.randn(100, 1)
        return (X, y, true_theta_simple)

    elif value == 2:
        # Multiple Linear Regression: y = 4 + 3x1 + 3x2 + 3x3 + noise
        X = 2 * np.random.rand(100, 3)
        true_theta_multiple = np.array([4, 3, 3, 3]).reshape(-1, 1)
        y = 4 + 3*X[:, 0] + 3*X[:, 1] + 3*X[:, 2] + np.random.randn(100)
        y = y.reshape(-1, 1)
        return (X, y, true_theta_multiple)

    else:
        return "Invalid choice. Please select 1 or 2."

# Get user input
choice = int(input("Enter 1 or 2: "))

result = switch_example(choice)

if isinstance(result, tuple):
    X, y, true_theta = result
    print("\nSelected Option:", choice)
    print("X shape:", X.shape)
    print("y shape:", y.shape)
    print("True Theta:\n", true_theta)
else:
    print(result)


Choose which Linear Regression you want to go for:
1. Simple Linear Regression
2. Multiple Linear Regression


Enter 1 or 2:  2



Selected Option: 2
X shape: (100, 3)
y shape: (100, 1)
True Theta:
 [[4]
 [3]
 [3]
 [3]]


In [82]:
#Numbers of rows
m = len(y)
print(m)

100


In [83]:
# --- Split into train (80) and test (20) ---
split_idx = int(0.8 * m)
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]


In [84]:
# Add bias term
X_train_b = np.c_[np.ones((len(X_train), 1)), X_train] 

X_test_b = np.c_[np.ones((len(X_test), 1)), X_test]    


In [85]:
class GDRegressor:

    def __init__(self, learning_rate=0.1, epochs=100):
        self.learning_rate = learning_rate   
        self.epochs = epochs
        self.theta = None

    def fit(self, X_train, y_train):
        # Initialize theta
        self.theta = np.random.randn(X_train.shape[1], 1)
        
        for i in range(self.epochs):
            y_pred_train = X_train.dot(self.theta)
            g = (2 / len(y_train)) * X_train.T.dot(y_pred_train - y_train)
            self.theta = self.theta - self.learning_rate * g
            
        print("\nPredicted Theta:\n", self.theta)
        
    def predict(self, X_test):
        X_b = np.c_[np.ones((X_test.shape[0], 1)), X_test]
        return X_b.dot(self.theta)
         

    def mse(self, y_true, y_pred):
        #Compute Mean Squared Error
        return np.mean((y_true - y_pred) ** 2)


In [86]:
gd = GDRegressor(learning_rate = 0.1, epochs = 1290);

In [87]:
gd.fit(X_train_b,y_train)


Predicted Theta:
 [[4.31766335]
 [3.06988777]
 [3.08530714]
 [2.68993714]]


In [88]:
y_pred = gd.predict(X_test)

mse_value = gd.mse(y_test, y_pred)
print("\nMSE:", mse_value)


MSE: 1.5385119326466823


In [89]:
def showTrueTheta():
    if(choice == 1):
        print("True theta Simple Linear Regression:\n", true_theta)
    else:
        print("True theta Multiple Linear Regression:\n", true_theta)

showTrueTheta()

True theta Multiple Linear Regression:
 [[4]
 [3]
 [3]
 [3]]


In [90]:
class SGDRegressor:

    def __init__(self, learning_rate = 0.1, epochs = 100):
        self.learning_rate = learning_rate   
        self.epochs = epochs
        self.theta = None

    def fit(self, X_train, y_train):
        # Initialize theta
        self.theta = np.random.randn(X_train.shape[1], 1)
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                
                idx = np.random.randint(0, X_train.shape[0])
                
                X_train_1_row = X_train[ idx : idx + 1]
                y_train_1_row = y_train[ idx : idx + 1]

                y_pred_train = X_train_1_row.dot(self.theta)
                
                g = 2 * X_train_1_row.T.dot( y_pred_train - y_train_1_row )
                
                self.theta = self.theta - self.learning_rate * g
        print("\nPredicted Theta:\n", self.theta)
        
    def predict(self, X_test):
        X_b = np.c_[np.ones((X_test.shape[0], 1)), X_test]
        return X_b.dot(self.theta)
        

    def mse(self, y_true, y_pred):
        #Compute Mean Squared Error
        return np.mean((y_true - y_pred) ** 2)


In [91]:
sgdr = SGDRegressor(learning_rate = 0.01, epochs = 609);

In [92]:
sgdr.fit(X_train_b, y_train)


Predicted Theta:
 [[4.44774961]
 [2.86179861]
 [3.47129158]
 [2.67051953]]


In [93]:
y_pred = sgdr.predict(X_test)

mse_value = sgdr.mse(y_test, y_pred)
print("\nMSE:", mse_value)


MSE: 1.9593463849174182


In [94]:
showTrueTheta()

True theta Multiple Linear Regression:
 [[4]
 [3]
 [3]
 [3]]


In [95]:
class MBGDRegressor:

    def __init__(self, learning_rate=0.1, epochs=100, batch_size=32):
        self.learning_rate = learning_rate   
        self.epochs = epochs
        self.batch_size = batch_size
        self.theta = None

    def fit(self, X_train, y_train):
        n_samples, n_features = X_train.shape
        self.theta = np.random.randn(X_train.shape[1], 1)

        for i in range(self.epochs):
            # Shuffle data
            indices = np.arange(X_train.shape[0])
            np.random.shuffle(indices)
            X_train = X_train[indices]
            y_train = y_train[indices]

            # Process in mini-batches
            for start_idx in range(0, n_samples, self.batch_size):
                end_idx = start_idx + self.batch_size
                X_batch = X_train[start_idx:end_idx]
                y_batch = y_train[start_idx:end_idx]

                y_pred = X_batch.dot(self.theta)

                # Gradient of MSE loss
                g = (2 / len(y_batch)) * X_batch.T.dot(y_pred - y_batch)

                # Update theta
                self.theta = self.theta - self.learning_rate * g

        print("\nPredicted Theta:\n", self.theta)

    def predict(self, X_test):
        X_b = np.c_[np.ones((X_test.shape[0], 1)), X_test]
        return X_b.dot(self.theta)
        
    def mse(self, y_true, y_pred):
        #Compute Mean Squared Error
        return np.mean((y_true - y_pred) ** 2)

   

In [96]:
mbgd = MBGDRegressor(learning_rate=0.01, epochs=51, batch_size=int(X_train_b.shape[0]/10))

In [97]:
mbgd.fit(X_train_b,y_train)


Predicted Theta:
 [[3.85254596]
 [3.14905997]
 [3.2380411 ]
 [2.88098723]]


In [98]:
y_pred = mbgd.predict(X_test)

mse_value = mbgd.mse(y_test, y_pred)
print("\nMSE:", mse_value)


MSE: 1.443147741965773


In [99]:
showTrueTheta()

True theta Multiple Linear Regression:
 [[4]
 [3]
 [3]
 [3]]
