**Practical-9**

**Aim: Implement Ex-OR Gate/any other problem using Backpropagation Neural Networks (Self-Implementation)**. 

In [20]:
import numpy as np

# XOR input and output
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Activation function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    # x is already sigmoid(x)
    return x * (1 - x)

# Initialize weights
np.random.seed(42)
w1 = np.random.uniform(size=(2, 2))   # input to hidden
b1 = np.random.uniform(size=(1, 2))   # hidden bias
w2 = np.random.uniform(size=(2, 1))   # hidden to output
b2 = np.random.uniform(size=(1, 1))   # output bias

lr = 0.15  # learning rate
epochs = 200000

# Training loop (backpropagation)
for epoch in range(epochs):

    # Forward pass
    z1 = np.dot(X, w1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, w2) + b2
    a2 = sigmoid(z2)

    # Error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_w2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, w2.T) * sigmoid_derivative(a1)
    d_w1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update weights
    w1 += lr * d_w1
    b1 += lr * d_b1
    w2 += lr * d_w2
    b2 += lr * d_b2

# Final output after training
print("Final predictions:")
print(a2.round(3))


Final predictions:
[[0.007]
 [0.994]
 [0.994]
 [0.006]]


In [21]:
import numpy as np

# XOR dataset
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Sigmoid activation
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(a):
    return a * (1 - a)

# Neural Network Training
def train_XOR(X, y, hidden_units=2, lr=0.5, epochs=10000):
    np.random.seed(42)

    n_x = 2
    n_h = hidden_units
    n_y = 1
    
    # Initialize weights
    W1 = np.random.randn(n_h, n_x)
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h)
    b2 = np.zeros((n_y, 1))

    for i in range(epochs):
        # Forward pass
        Z1 = np.dot(W1, X.T) + b1
        A1 = sigmoid(Z1)

        Z2 = np.dot(W2, A1) + b2
        A2 = sigmoid(Z2)

        # Compute loss
        m = y.shape[0]
        loss = np.mean((y.T - A2)**2)

        # Backpropagation
        dZ2 = (A2 - y.T) * sigmoid_derivative(A2)
        dW2 = (1/m) * np.dot(dZ2, A1.T)
        db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)

        dZ1 = np.dot(W2.T, dZ2) * sigmoid_derivative(A1)
        dW1 = (1/m) * np.dot(dZ1, X)
        db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

        # Update weights
        W1 -= lr * dW1
        b1 -= lr * db1
        W2 -= lr * dW2
        b2 -= lr * db2

        if i % 2000 == 0:
            print(f"Epoch {i} | Loss: {loss:.4f}")

    return W1, b1, W2, b2

# Prediction
def predict(X, W1, b1, W2, b2):
    Z1 = np.dot(W1, X.T) + b1
    A1 = sigmoid(Z1)

    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)

    return (A2 > 0.5).astype(int)

# Train XOR model
W1, b1, W2, b2 = train_XOR(X, y)

# Test
preds = predict(X, W1, b1, W2, b2)

print("\nXOR Predictions:")
print(preds.T)


Epoch 0 | Loss: 0.2566
Epoch 2000 | Loss: 0.1819
Epoch 4000 | Loss: 0.0157
Epoch 6000 | Loss: 0.0048
Epoch 8000 | Loss: 0.0027

XOR Predictions:
[[0]
 [1]
 [1]
 [0]]


In [1]:
import numpy as np

# XOR dataset
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])        # shape = (4,2)

y = np.array([[0],
              [1],
              [1],
              [0]])         # shape = (4,1)

# Sigmoid activation
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(a):
    return a * (1 - a)

# Binary Cross-Entropy (Logit Loss)
def logit_loss(y, y_hat):
    m = y.shape[0]
    return -np.mean(y * np.log(y_hat + 1e-8) + (1 - y) * np.log(1 - y_hat + 1e-8))

# Neural Network Training
def train_XOR_logit(X, y, hidden_units=2, lr=0.1, epochs=10000):
    np.random.seed(42)

    n_x = 2
    n_h = hidden_units
    n_y = 1
    
    # Initialize weights
    W1 = np.random.randn(n_h, n_x)
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h)
    b2 = np.zeros((n_y, 1))

    m = y.shape[0]

    for i in range(epochs):
        # Forward pass
        Z1 = np.dot(W1, X.T) + b1
        A1 = sigmoid(Z1)

        Z2 = np.dot(W2, A1) + b2
        A2 = sigmoid(Z2)

        # Compute logit loss
        loss = logit_loss(y, A2.T)

        # Backpropagation using BCE derivatives
        dZ2 = A2 - y.T              # derivative of BCE for sigmoid
        dW2 = (1/m) * np.dot(dZ2, A1.T)
        db2 = (1/m) * np.sum(dZ2, axis=1, keepdims=True)

        dZ1 = np.dot(W2.T, dZ2) * sigmoid_derivative(A1)
        dW1 = (1/m) * np.dot(dZ1, X)
        db1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)

        # Update parameters
        W1 -= lr * dW1
        b1 -= lr * db1
        W2 -= lr * dW2
        b2 -= lr * db2

        if i % 2000 == 0:
            print(f"Epoch {i} | Loss: {loss:.4f}")

    return W1, b1, W2, b2

# Prediction
def predict(X, W1, b1, W2, b2):
    Z1 = np.dot(W1, X.T) + b1
    A1 = sigmoid(Z1)

    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)

    return (A2 > 0.5).astype(int)

# Train XOR model with Logit Loss
W1, b1, W2, b2 = train_XOR_logit(X, y)

# Test
preds = predict(X, W1, b1, W2, b2)

print("\nXOR Predictions:")
print(preds.T)


Epoch 0 | Loss: 0.7065
Epoch 2000 | Loss: 0.6043
Epoch 4000 | Loss: 0.1989
Epoch 6000 | Loss: 0.0469
Epoch 8000 | Loss: 0.0247

XOR Predictions:
[[0]
 [1]
 [1]
 [0]]
