**Practical - 1**

**Aim : Hands-on Python Programming for Applied Machine Learning with NumPy for Data Representation and Numerical Computations.**

**Exercise - 1**

**Create Vectors**

In [1]:
#Import libraries
import numpy as np

In [2]:
print("Creating Vector Row: ");
list1 = [1,2,3,4,5];
vector_row = np.array(list1);
print(vector_row);

print("\nCreating Vector Column");
list2 = [[1],
         [2],
         [3],
         [4]
        ];
vector_column = np.array(list2);
print(vector_column);

Creating Vector Row: 
[1 2 3 4 5]

Creating Vector Column
[[1]
 [2]
 [3]
 [4]]


**Create Matrix**

In [3]:
print("Creating Matrix :");
list2 = [ [3,4],
         [2,7],
         [6,3],
         [3,1] ];
matrix = np.array(list2);
print(matrix);

print("\nExtracting elements from matrix of 4 rows and 2 columns : ");
print(matrix[0][1]);
print(matrix[1][0]);
print(matrix[2][1]);

print("\nAnother way to create a matrix using np.mat() { Not recommended to use because the majority of numpy operations return arrays and array is de facto standards. } :"); 
matrix_object = np.mat([[4,5,6],
                        [7,2,3],
                        [2,6,8]]);
print(matrix_object);

Creating Matrix :
[[3 4]
 [2 7]
 [6 3]
 [3 1]]

Extracting elements from matrix of 4 rows and 2 columns : 
4
2
3

Another way to create a matrix using np.mat() { Not recommended to use because the majority of numpy operations return arrays and array is de facto standards. } :
[[4 5 6]
 [7 2 3]
 [2 6 8]]


**Create a Sparse matrix** ||
**Sparse Matrix :**
A sparse matrix only represents non-zero values of a matrix. Here, we use the compressed sparse row (CSR) format to create a sparse matrix.

In [4]:
from scipy import sparse

print(" SMALL SPARSE MATRIX ");
matrix = np.array([[0,1],
                  [1,0],
                  [0,0]]);
small_sparse_matrix = sparse.csr_matrix(matrix);
print(small_sparse_matrix);

print("\nLARGE SPARSE MATRIX ")
new_matrix = np.array([[5,0,0,0,5],[0,0,0,0,6],[0,0,0,0,7]]);
large_sparse_matrix = sparse.csr_matrix(new_matrix);
print(large_sparse_matrix);

 SMALL SPARSE MATRIX 
  (0, 1)	1
  (1, 0)	1

LARGE SPARSE MATRIX 
  (0, 0)	5
  (0, 4)	5
  (1, 4)	6
  (2, 4)	7


**Selecting Elements of matrix**

In [5]:
list = [[77,88,99,100,110],[44,55,66,120,130],[11,22,33,140,150],[160,170,180,190,200]];
selected_matrix = np.array(list);
print(selected_matrix[2,2]);
print(selected_matrix[0,1]);
print(selected_matrix[3,0]);

print("Printing all rows and all columns");
print(selected_matrix[:,:]);

print("\nPrinting Two rows and all columns");
print(selected_matrix[:2,:]);

print("\nPrinting Two rows and 2 columns");
print(selected_matrix[:2,:2]);

33
88
160
Printing all rows and all columns
[[ 77  88  99 100 110]
 [ 44  55  66 120 130]
 [ 11  22  33 140 150]
 [160 170 180 190 200]]

Printing Two rows and all columns
[[ 77  88  99 100 110]
 [ 44  55  66 120 130]]

Printing Two rows and 2 columns
[[77 88]
 [44 55]]


In [6]:
print("\nPrinting all rows and 1 columns");
print(selected_matrix[:,:1]);

print("\nPrinting two rows and second column to fifth column");
print(selected_matrix[:2,2:5]);

print("\nPrinting three rows and fifth column");
print(selected_matrix[:3,4:5]);

print("\nPrinting all rows and third column");
print(selected_matrix[:,2:3]);


Printing all rows and 1 columns
[[ 77]
 [ 44]
 [ 11]
 [160]]

Printing two rows and second column to fifth column
[[ 99 100 110]
 [ 66 120 130]]

Printing three rows and fifth column
[[110]
 [130]
 [150]]

Printing all rows and third column
[[ 99]
 [ 66]
 [ 33]
 [180]]


**Describing shape, size and dimension of matrix**

In [7]:
matrix = np.array([[7,5,6,2,4,8],
                   [4,5,8,9,3,1],
                   [1,0,6,3,7,3]]);

print("Total number of rows and columns : ", matrix.shape);
print("Size of matrix : ", matrix.size);
print("Dimensions of matrix : ", matrix.ndim);

Total number of rows and columns :  (3, 6)
Size of matrix :  18
Dimensions of matrix :  2


**Applying operations on matrix**

In [8]:
matrix = np.array([[7,5,6,2,4,8],
                   [4,5,8,9,3,1],
                   [1,0,6,3,7,3]]);

multiply_100 = lambda i: i*100;

vectorised_multiply_100 = np.vectorize(multiply_100);

print("Multiply 100 to each element of matrix by using vectorize function : ")
print(vectorised_multiply_100(matrix));

print("\nAnother way to multiply matrix using broadcasting which allows to perform operations between the array even if there dimensions are not same:");
print(matrix*100);

print("\nAdding 10 to each element of matrix :");
print(matrix+10);


Multiply 100 to each element of matrix by using vectorize function : 
[[700 500 600 200 400 800]
 [400 500 800 900 300 100]
 [100   0 600 300 700 300]]

Another way to multiply matrix using broadcasting which allows to perform operations between the array even if there dimensions are not same:
[[700 500 600 200 400 800]
 [400 500 800 900 300 100]
 [100   0 600 300 700 300]]

Adding 10 to each element of matrix :
[[17 15 16 12 14 18]
 [14 15 18 19 13 11]
 [11 10 16 13 17 13]]


**Finding MINIMUM AND MAXIMUM in matrix**

In [9]:
matrix = np.array([[7,5,6,],
                   [4,5,8],
                   [1,3,6]]);

print("Maximum element in Matrix : ", np.max(matrix));
print("Minimum element in Matrix : ", np.min(matrix));

#axis = 0 : column 
print("Minimum element in each column of matrix : ", np.min(matrix,axis=0));
print("Maximum element in each column of matrix : ", np.max(matrix,axis=0));

#axis = 1 : row 
print("Minimum element in each row of matrix : ", np.min(matrix,axis=1));
print("Maximum element in each row of matrix : ", np.max(matrix,axis=1));


Maximum element in Matrix :  8
Minimum element in Matrix :  1
Minimum element in each column of matrix :  [1 3 6]
Maximum element in each column of matrix :  [7 5 8]
Minimum element in each row of matrix :  [5 4 1]
Maximum element in each row of matrix :  [7 8 6]


**Mean, Variance and standard deviation of matrix**

In [10]:
matrix = np.array([[1,2,6,],
                   [4,6,8],
                   [9,3,7]]);

print("Mean", np.mean(matrix));
print("Variance", np.var(matrix));
print("Standard Deviation", np.std(matrix));

print("Mean of each column",np.mean(matrix,axis=0));
print("Mean of each rows",np.mean(matrix,axis=1));

Mean 5.111111111111111
Variance 6.765432098765432
Standard Deviation 2.601044424604361
Mean of each column [4.66666667 3.66666667 7.        ]
Mean of each rows [3.         6.         6.33333333]


**Reshaping Array** || **Reshape**: It is used to restructure an array to mainatain the same data but it is organised as number  of rows and columns. One condition to be remember is that newly reshaped matrix should have same numbers of elements. We can check numbers of elements using matrix.size.

In [11]:
matrix = np.array([[1,2,6,4],
                   [4,6,8,7],
                   [9,3,7,1],
                   [4,5,9,3]]);

print("Reshaping array to 2 rows and 8 columns: ")
print(matrix.reshape(2,8))

print("\nReshaping array to 1 row and 16 columns: ")
print(matrix.reshape(1,16))

print("\nReshaping array to 1 row and all column using matrix.reshape(1,-1)");
print(matrix.reshape(1,-1))

print("\nChange 2D array to 1D array");
print(matrix.reshape(16));

Reshaping array to 2 rows and 8 columns: 
[[1 2 6 4 4 6 8 7]
 [9 3 7 1 4 5 9 3]]

Reshaping array to 1 row and 16 columns: 
[[1 2 6 4 4 6 8 7 9 3 7 1 4 5 9 3]]

Reshaping array to 1 row and all column using matrix.reshape(1,-1)
[[1 2 6 4 4 6 8 7 9 3 7 1 4 5 9 3]]

Change 2D array to 1D array
[1 2 6 4 4 6 8 7 9 3 7 1 4 5 9 3]


**Transpose of a matrix** || **Transpose** : Swapping row and column indices. Technically vectors cannot be transposed because it is just the collections of values.

In [12]:
matrix = np.array([[1,2,6,4],
                   [4,6,8,7],
                   [9,3,7,1],
                   [4,5,9,3]]);

print("Transpose of array : ")
print(matrix.T)

print("\nTranspose of 1D array { It remains same }");
print(np.array([1,2,3,4,5]).T)

print("\nTransposing a row vector to column vector");
print(np.array([[1,2,3,4,5]]).T);

Transpose of array : 
[[1 4 9 4]
 [2 6 3 5]
 [6 8 7 9]
 [4 7 1 3]]

Transpose of 1D array { It remains same }
[1 2 3 4 5]

Transposing a row vector to column vector
[[1]
 [2]
 [3]
 [4]
 [5]]


**Flattening the matrix** || means converting it in 1D array or row vector

In [13]:
matrix = np.array([[1,2,3],
                   [7,8,9],
                   [4,5,6]]);

print("Flattening the matrix means converting it in 1D array");
print(matrix.flatten());

print("\nReshaping matrix to row vector");
print(matrix.reshape(1,-1));


Flattening the matrix means converting it in 1D array
[1 2 3 7 8 9 4 5 6]

Reshaping matrix to row vector
[[1 2 3 7 8 9 4 5 6]]


**Rank of matrix**  || **Rank:** Dimensions of vector space spanned by columns and rows.

In [14]:
matrix = np.array([[1,2,3],
                   [7,8,9],
                   [4,5,6]]);

print("Rank of matrix: ",np.linalg.matrix_rank(matrix));

Rank of matrix:  2


**Determinant of matrix**

In [15]:
matrix = np.array([[1,7,3],
                   [3,4,8],
                   [9,5,2]]);

print("Determinant of matrix: ",np.linalg.det(matrix));


Determinant of matrix:  367.0000000000001


**Diagonal of matrix**

In [16]:
matrix = np.array([[1,7,3],
                   [3,4,8],
                   [9,5,2]]);

print("Diagonal of matrix : ", matrix.diagonal());

print("\nOne Element above diagonal of matrix :", matrix.diagonal(offset=1));

print("\nOne Element below diagonal of matrix :", matrix.diagonal(offset=-1));

Diagonal of matrix :  [1 4 2]

One Element above diagonal of matrix : [7 8]

One Element below diagonal of matrix : [3 5]


**Trace of matrix** || **Trace:** Sum of diagonal elements

In [17]:
matrix = np.array([[1,7,3],
                   [3,4,8],
                   [9,5,2]]);

print("Trace: sum of all diagonal element");
print(matrix.trace());

print("\nAnother method to find Trace: sum of all diagonal element");
print(sum(matrix.diagonal()));

Trace: sum of all diagonal element
7

Another method to find Trace: sum of all diagonal element
7


**Finding Eigen Value and Eigen Vector**

In [18]:
matrix = np.array([[1,7,3],
                   [3,4,8],
                   [9,5,2]]);

eigenvalues, eigenvectors = np.linalg.eig(matrix);
print("Eigen Values: ",eigenvalues);
print("Eigen Vectors: ",eigenvectors);

Eigen Values:  [14.09645743+0.j        -3.54822871+3.6667401j -3.54822871-3.6667401j]
Eigen Vectors:  [[ 0.47673341+0.j          0.159821  -0.48046368j  0.159821  +0.48046368j]
 [ 0.62856814+0.j          0.42188209+0.39589725j  0.42188209-0.39589725j]
 [ 0.61451391+0.j         -0.63944723+0.j         -0.63944723-0.j        ]]


**Calculating Dot Product**

In [19]:
vector_a = np.array([1,7,3]);
vector_b = np.array([2,3,4]);

print("Dot Product: ", np.dot(vector_a,vector_b));

print("\nAnother Method for Dot Product: ", vector_a @ vector_b);

Dot Product:  35

Another Method for Dot Product:  35


**Adding and Subtracting the matrix**

In [20]:
matrix_a = np.array([[2,2,2,2],[4,4,4,4],[1,1,1,1]]);
matrix_b = np.array([[3,3,3,3],[5,5,5,5],[1,1,1,1]]);

print("Adding the matrix");
print(np.add(matrix_a,matrix_b));

print("Another way of adding the matrix");
print(matrix_a + matrix_b);

print("Subtracting the matrix");
print(np.subtract(matrix_a,matrix_b));

print("Another way of subtracting the matrix");
print(matrix_a - matrix_b);

Adding the matrix
[[5 5 5 5]
 [9 9 9 9]
 [2 2 2 2]]
Another way of adding the matrix
[[5 5 5 5]
 [9 9 9 9]
 [2 2 2 2]]
Subtracting the matrix
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 0  0  0  0]]
Another way of subtracting the matrix
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 0  0  0  0]]


**Multiplying the matrix**

In [21]:
matrix_1 = np.array([[1,1],[1,2]]);
matrix_2 = np.array([[1,3],[1,2]]);

print("Multiplying the matrix");
print(np.dot(matrix_1,matrix_2));

print("\nAnother way of Multiplying the matrix");
print(matrix_1 @ matrix_2);


Multiplying the matrix
[[2 5]
 [3 7]]

Another way of Multiplying the matrix
[[2 5]
 [3 7]]


**Inverting the matrix**

In [22]:
matrix = np.array([[1,4],[2,5]]);

print("Inverting the matrix");
print(np.linalg.inv(matrix));

print("\nCreate a Identity Matrix ( A*A^-1 = I): ");
print(matrix @ np.linalg.inv(matrix));

Inverting the matrix
[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]

Create a Identity Matrix ( A*A^-1 = I): 
[[1. 0.]
 [0. 1.]]


**Generating Random Values**

In [23]:
print("Generate the three random float values from 0.0 to 1.0");
np.random.seed(0)
print(np.random.random(3))

np.random.seed(42)
print("\nFirst sequence with seed 42:", np.random.rand(3))

print("\nGenerate three random element from 1 to 10 ");
print(np.random.randint(0,11,3));

print("\nRandom Normal distribution values");
print(np.random.normal(0.0,1.0,3));

print("\nRandom Logistic distribution values");
print(np.random.logistic(0.0,1.0,3));

print("\nRandom Uniform distribution values");
print(np.random.uniform(1.0,2.0,3));

Generate the three random float values from 0.0 to 1.0
[0.5488135  0.71518937 0.60276338]

First sequence with seed 42: [0.37454012 0.95071431 0.73199394]

Generate three random element from 1 to 10 
[4 6 9]

Random Normal distribution values
[ 0.27904129  1.01051528 -0.58087813]

Random Logistic distribution values
[-1.49344971 -0.82717731  0.09910677]

Random Uniform distribution values
[1.43194502 1.29122914 1.61185289]


**Exercise 2**

**1. Import numpy package as np**

In [1]:
import numpy as np

**2. Print numpy version and configuration**

In [4]:
print(np.__version__);
np.show_config();

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/lenovo/anaconda3/Library/include
    lib directory: C:/Users/lenovo/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:


**3. Create a null vector of size 15**

In [5]:
Z = np.zeros(15);
print(Z);

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Finding Memory size of array** 

In [2]:
Z = np.zeros((10,10));
print(Z)
print("%d bytes" % ( Z.size * Z.itemsize));

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 bytes


**5. How to get documentation of numpy add function from command line ?**

In [7]:
!python -c "import numpy; import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**6. Create a null vector of size 10 but fifth value is 1**

In [8]:
Z = np.zeros(10);
Z[4] = 1;
print(Z);

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Create a vector with values ranging from 10 to 49**

In [9]:
A = np.arange(10,50);
print(A);

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**8. Reverse a vector (first element becomes last)**

In [4]:
A = np.arange(50);
# A = A[1: 20:];
# print(A);
A = A[::-1];
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [11]:
A = np.arange(9).reshape(3,3);
print(A);

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**10. Find the indices of non zero elements from [4,5,9,3]**

In [12]:
A = np.nonzero([4,5,0,3]);
print(A);

(array([0, 1, 3], dtype=int64),)


**11. Create a 3X3 identity matrix** 

In [13]:
A = np.eye(3);
print(A);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**12. Create a 3x3x3 array with random values**

In [14]:
A = np.random.random((3,3,3));
print(A);

[[[0.09240413 0.58762149 0.20186657]
  [0.91273772 0.51487201 0.27176337]
  [0.0350491  0.88416996 0.42825333]]

 [[0.67648309 0.05310401 0.05020724]
  [0.9361564  0.095687   0.8791867 ]
  [0.10113299 0.79560065 0.319135  ]]

 [[0.85019471 0.10189796 0.18579322]
  [0.79645988 0.77650086 0.27638019]
  [0.88553368 0.45614671 0.49805924]]]


**13. Create a 10x10 array with random values and find minimum and maximum element in array**

In [15]:
A = np.random.random((10,10));
# print(A);
Amin, Amax = A.min(), A.max();
print(Amin,Amax);

0.008362575466108635 0.9987732070345411


**14. Create a random vector of size 30 and find the mean.**

In [16]:
A = np.random.random(30);
print(A);
mean = A.mean();
print("Mean: ",mean);

[0.76157796 0.77140643 0.00271474 0.00803169 0.71975727 0.14608475
 0.74831219 0.67058514 0.958581   0.86630677 0.83970732 0.68159871
 0.74489561 0.57238742 0.92225395 0.91701223 0.37248743 0.73621101
 0.65501468 0.50708804 0.03109441 0.71969564 0.4313581  0.34180363
 0.30972919 0.35221171 0.02076294 0.28430724 0.01110195 0.82330377]
Mean:  0.530912763432521


**15. Create a 2D array with 1 on the border and 0 inside**

In [17]:
S1 = np.array([4,5,6,7,8,9]);
print("Starting from 1 index to second last index elements are printed : ");
print(S1[1:-1]);

S2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]);
print(S2[::,::]);
# print(S2[1::2,::2]);
print("Starting from 1 index to second last element of 2D array are printed : ");
print( S2[1:-1,:]);

print("Starting from 1 index to second last element of array present inside the outer array are printed");
print(S2[:,1:-1]);

print("Printing only inner element of inner array ([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]) where we ignored zero index and last index. Also in outer array we ignored zero and last index.");
print(S2[1:-1,1:-1]);

print("Changing inner element with zeros : ");
S2[1:-1,1:-1] = 0;
print(S2);

A = np.ones((10,10));
print("Only ones in 10x10 matrix : ");
print(A);

print("Changing inner element with zeros : ");
A[1:-1, 1:-1] = 0;
print(A);

Starting from 1 index to second last index elements are printed : 
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Starting from 1 index to second last element of 2D array are printed : 
[[ 5  6  7  8]
 [ 9 10 11 12]]
Starting from 1 index to second last element of array present inside the outer array are printed
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
Printing only inner element of inner array ([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]) where we ignored zero index and last index. Also in outer array we ignored zero and last index.
[[ 6  7]
 [10 11]]
Changing inner element with zeros : 
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]
Only ones in 10x10 matrix : 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1

**16 Adding 0 in boundary of 2D array.**

In [18]:
A = np.ones((5,5));
print(A);
A = np.pad(A, pad_width = 2, mode='constant', constant_values = 0);
print(A);

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**17. What is the result of the following expression ?**

In [19]:
print(np.nan);
print(0*np.nan);
print(np.nan == np.nan);
print(np.inf);
print(np.inf > np.nan);
print(np.nan - np.nan);
print(np.nan in set([np.nan]));
print(0.3);
print(3*0.1);
print(0.3 == 3*0.1);
print(np.inf > 100000000);

nan
nan
False
inf
False
nan
True
0.3
0.30000000000000004
False
True


**18. Create a 5X5 matrix with values 1,2,3,4 just below the diagonal** 

In [20]:
A = np.arange(25).reshape(5,5);
print(A);

print("Printing Main Diagonal: ");
print(A.diagonal());

print("Printing element below main diagonal: ");
print(A.diagonal(offset=-1));

print("Creating a matrix where elements below main diagonal are 1,2,3,4 : ");
Z= np.diag(1+np.arange(4),k=-1);
print(Z);

print("Creating a matrix where elements above main diagonal are 1,2,3,4 : ");
print(np.diag(1+np.arange(4),1));

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Printing Main Diagonal: 
[ 0  6 12 18 24]
Printing element below main diagonal: 
[ 5 11 17 23]
Creating a matrix where elements below main diagonal are 1,2,3,4 : 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
Creating a matrix where elements above main diagonal are 1,2,3,4 : 
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**19. Create a 8x8 matrix and fill it with checkboard pattern**

In [21]:
Z = np.zeros((8,8),dtype=int);
print("8X8 Matrix with zeros only: ");
print(Z);

print("1::2 means starts with 1 and take two step and stop when reached last row and ::2 means it will take 2 step in inner array but starts from 0 index:");
Z[1::2,::2]=1;
print(Z);

print("::2 means starts with 0 and take two step and stop when reached last row and 1::2 means it will take 2 step in inner array but starts from 1 index:");
Z[::2,1::2]=1;
print(Z);

8X8 Matrix with zeros only: 
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
1::2 means starts with 1 and take two step and stop when reached last row and ::2 means it will take 2 step in inner array but starts from 0 index:
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
::2 means starts with 0 and take two step and stop when reached last row and 1::2 means it will take 2 step in inner array but starts from 1 index:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20. Consider a (6,7,8) shape array, what is the index(x,y,z) of the 100th element?**

In [22]:
print(np.unravel_index(99,(6,7,8)));

(1, 5, 3)


**21. Create a checkboard pattern using tile function**

In [23]:
#(4,4) means it repeat the 2D array given 4 times along rows and 4 times along columns
z = np.tile(np.array([[1,0],[0,1]]),(4,4));
print(z);

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**22. Normalize a 5x5 matrix**

In [24]:
Z = np.random.random((5,5));
print(Z);
print("Mean : ",np.mean(Z));
print("Standard deviation : ",np.std(Z));
Z = ( Z - np.mean(Z) ) / (np.std(Z));
print(Z);

[[0.81863628 0.20775881 0.05395566 0.11369649 0.70093269]
 [0.82150272 0.83667239 0.98207591 0.11391355 0.91305849]
 [0.96785094 0.54778929 0.3663838  0.77616985 0.16264836]
 [0.72467671 0.91234825 0.58991857 0.78073194 0.17860491]
 [0.11040898 0.28441035 0.1670685  0.41345563 0.44149091]]
Mean :  0.5194463989360731
Standard deviation :  0.31588889518751473
[[ 0.94713643 -0.98670005 -1.47359007 -1.2844703   0.5745257 ]
 [ 0.95621063  1.0042328   1.46453236 -1.28378319  1.24604598]
 [ 1.41950081  0.08972425 -0.48454567  0.81270172 -1.12950485]
 [ 0.64969144  1.24379761  0.22309162  0.82714378 -1.07899167]
 [-1.29487748 -0.74404657 -1.11551216 -0.33553179 -0.24678135]]


**23. Given a 1d array, negate all elements which are betweeen 3 and 8, in place.**

In [25]:
Z=np.arange(11);
print(Z);
Z[ (3 < Z) & ( Z <= 8) ] *= -1
print(Z);

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


**24. Consider a interger vector Z which of these is legal ?**

In [26]:
Z = 4;
Z*Z
print(Z*Z);
print(2<<Z>>2);
print(Z <- Z);
print(1j*Z);
print(Z/1/1);
print(Z<Z>Z);

16
8
False
4j
4.0
False


**25. How to find the common values between two arrays ?**

In [27]:
z1 = np.random.randint(0,10,10);
print(z1);
z2 = np.random.randint(0,10,10);
print(z2);
print(np.intersect1d(z1,z2));

[6 9 1 5 9 9 3 6 7 0]
[2 8 8 4 5 1 8 5 7 7]
[1 5 7]


**26. How to get the dates of yesterday,today and tommorrow ?**

In [28]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D');
today = np.datetime64('today','D');
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D');
print(yesterday);
print(today);
print(tomorrow);

2025-09-22
2025-09-23
2025-09-24


**27. How to get all the dates of corresponding to the month of july 2016?**

In [29]:
Z = np.arange('2016-07','2016-08', dtype='datetime64[D]');
print(Z);

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**28. Extract the integer part of random array using 5 different methods**

In [30]:
Z = np.random.uniform(0,10,10);
print(Z);
print(Z%1);
print(Z - Z%1);
print(np.floor(Z));
print(np.ceil(Z));
print(Z.astype(int));
print(np.trunc(Z));

[2.50277619e+00 1.19536938e-03 8.36607483e+00 4.75223105e+00
 1.58477951e+00 3.30583875e+00 3.97497867e+00 1.61792978e+00
 6.12613625e+00 9.70413300e+00]
[0.50277619 0.00119537 0.36607483 0.75223105 0.58477951 0.30583875
 0.97497867 0.61792978 0.12613625 0.704133  ]
[2. 0. 8. 4. 1. 3. 3. 1. 6. 9.]
[2. 0. 8. 4. 1. 3. 3. 1. 6. 9.]
[ 3.  1.  9.  5.  2.  4.  4.  2.  7. 10.]
[2 0 8 4 1 3 3 1 6 9]
[2. 0. 8. 4. 1. 3. 3. 1. 6. 9.]


**29. Create a 5x5 matrix with row values ranging from 0 to 4.**

In [31]:
Z = np.zeros((5,5));
Z += np.arange(5);
print(Z);

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**30. Create a random vector of size 10 and sort it.**

In [32]:
A = np.random.random(10);
A.sort();
print(A);


[0.15261799 0.175391   0.29658345 0.46110399 0.56456554 0.59651797
 0.61190773 0.65524313 0.7504567  0.99557634]


**31. Consier two random array  A and D and check if they are equal.**

In [33]:
A = np.random.randint(0,2,5);
B = np.random.randint(0,2,5);
print(A,B);

#Assuming the identical shape of arrays and a tolerance for the comparisons for the values
equal = np.allclose(A,B);
print(equal);

#checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B);
print(equal);

[1 1 1 0 1] [1 1 0 1 0]
False
False


**32. Make an array immutable (read-only)**

In [34]:
A = np.zeros(10);
A.flags.writeable = False;
# A[0]=1;
# print(A); #Value error assignment destination is readonly.

**33. Print the minimum and maximum representable value for each numpy scalar type**

In [35]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min);
   print(np.iinfo(dtype).max);

for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min);
   print(np.finfo(dtype).max);
   print(np.finfo(dtype).eps);

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


**34. How to find the closest value (to a given scalar) in a vector ?**

In [36]:
Z = np.arange(100);
v = np.random.uniform(0,100);
print(v);
index = (np.abs(Z-v)).argmin();
print(Z[index]);

91.3307943390751
91


**35. Consider a random vector of shape (3,2) representing coordinates, find point by point distances**

In [37]:
Z = np.random.random((3,2));
print(Z);

X,Y = np.atleast_2d(Z[:,0], Z[:,1]);
distance  = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2 );
print(distance);

import scipy
import scipy.spatial

Z = np.random.random((3,2));
D = scipy.spatial.distance.cdist(Z,Z);
print(D);

[[0.36893805 0.85921595]
 [0.88334066 0.91174439]
 [0.53823901 0.58064046]]
[[0.         0.51707764 0.32598638]
 [0.51707764 0.         0.47825198]
 [0.32598638 0.47825198 0.        ]]
[[0.         0.2585343  0.23844037]
 [0.2585343  0.         0.31082856]
 [0.23844037 0.31082856 0.        ]]


**36. How to convert a float(32 bits) array into an integer (32 bits) in place ?**

In [38]:
A = np.arange(10, dtype=np.float32);
print(A);
A = A.astype(np.int32, copy=False);
print(A);

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


**37. How to read the following file ?**

In [39]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                 6, , , 7, 8\n
                 , , 9,10,11\n""");
Z = np.genfromtxt(s, 
                  delimiter="," ,
                  dtype=np.int32,
                  filling_values=-1
                 );
print(Z);

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


**38. Subtract the mean of each row of the matrix**

In [40]:
X = np.random.rand(5,10);

#new versions
Y = X - X.mean(axis = 1, keepdims = True);

#older versions
# Y = X - X.mean(axis = 1).reshape(-1,1);

print(Y);

[[ 0.0012356  -0.34460666 -0.34785502  0.10545217 -0.13856579  0.48271161
   0.06761203  0.18723819 -0.19887066  0.18564854]
 [-0.13809599 -0.18659571  0.03127611 -0.18966842  0.25667044  0.18582907
  -0.40704204  0.2940355   0.23544602 -0.08185497]
 [ 0.25465946 -0.38999719  0.15941946  0.02769286 -0.43945688  0.03681778
   0.27471678  0.07104406 -0.14144746  0.14655112]
 [ 0.13231552 -0.05410556 -0.19095724 -0.26573561  0.24022763 -0.30127084
   0.27568272  0.04255816  0.22013443 -0.09884921]
 [-0.45897638  0.3523091  -0.03579027 -0.5647903   0.29999969  0.24306187
   0.2152623   0.21449345  0.09749138 -0.36306084]]


**39. How to sort an aray by the nth column?**

In [41]:
Z = np.random.randint(0,10,(3,3));
print(Z);
print(Z[Z[:,1].argsort()])

[[0 3 2]
 [2 7 9]
 [2 4 8]]
[[0 3 2]
 [2 4 8]
 [2 7 9]]


**40. How to tell if a given 2D array has null columns ?**

In [42]:
S = np.random.randint(0,3,(3,10));
print(S);
print((~Z.any(axis = 0)).any());

[[2 2 1 0 2 0 0 0 2 1]
 [2 1 1 0 2 2 1 0 2 2]
 [0 0 1 2 0 2 0 2 1 2]]
False


**41. How to find the nearest value from a given value in an array**

In [43]:
Z = np.random.uniform(0,1,10);
print(Z);
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.52578494 0.28826318 0.76422617 0.64981857 0.0174549  0.05226372
 0.09802343 0.95938669 0.58976035 0.16849735]
0.5257849355542579


**42. How to accumulate elements of a vector X to an array F based on an index list I?**

In [44]:
X = [1,2,3,4,5,6];
I = [1,3,9,3,4,1]
F = np.bincount(I,weights = X);
print(F);

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


**43. How to get the diagonals of a dot product ?**

In [45]:
A = np.random.uniform(0,1,(5,5));
B = np.random.uniform(0,1,(5,5));

print(A);
print(B);
#slow
np.diag(np.dot(A,B));

#fast
np.sum(A*B.T, axis = 1);

#fastest
print(np.einsum("ij,ji->i",A,B));


[[0.78926458 0.27056167 0.33433958 0.13734523 0.84957933]
 [0.61773209 0.17570497 0.60790993 0.57504969 0.59467069]
 [0.25225546 0.9262957  0.83291386 0.14533873 0.56688137]
 [0.61943959 0.87597199 0.77307922 0.64445724 0.7755123 ]
 [0.48193749 0.97533103 0.27561674 0.96075697 0.22262041]]
[[0.47044362 0.57340877 0.6787025  0.84887491 0.1607911 ]
 [0.58775077 0.23262957 0.09446838 0.94230486 0.56246955]
 [0.85972774 0.87614274 0.04266175 0.79061962 0.70688487]
 [0.13087638 0.22171397 0.72251008 0.73027865 0.54378132]
 [0.01045556 0.86790819 0.39013392 0.72980123 0.25408894]]
[0.8446264  1.57131916 0.62041398 2.99907418 1.39992164]


**44. Consider the vector [1,2,3,4,5], how to build a new vector with 3 consecutive zeros interleaved between each values?**

In [46]:
A = np.array([1,2,3,4,5]);
na = 3

A0 = np.zeros(len(A) + (len(A) - 1)*(na));
A0[::na + 1] = A;
print(A0);

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**45. How to swap two rows of an array ?**

In [47]:
A = np.arange(25).reshape(5,5);
print(A);
A[[0,1]] = A[[1,0]]
print(A);

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**46. How to compute averages using a sliding window over an array ?**

In [48]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float);
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3));

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


**47. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i]) ?**  

In [49]:
def distance(P0,P1,p):
    T = P1 - P0;
    L = (T**2).sum(axis=1);
    U = -(( P0[:,0] - p[...,0] )*T[:,0] + (P0[:,1] - p[...,1] )*T[:,1]) / L;
    U = U.reshape(len(U),1);
    D = P0 + U*T - p;
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2));
P1 = np.random.uniform(-10,10,(10,2));
p = np.random.uniform(-10,10,(1,2));
print(distance(P0, P1, p));

[10.24755109  2.89012433  8.46840542  4.03364093  1.53797503  8.81904019
  1.7212362   5.04533362  4.4400043   1.18377189]


**48. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i ( P0[i],P1[i] ) ?**   

In [50]:
P0 = np.random.uniform(-10,10,(10,2));
P1 = np.random.uniform(-10,10,(10,2));
p = np.random.uniform(-10,10,(1,2));
print(np.array([distance(P0,P1,p_i) for p_i in p ]))

[[ 2.11023241  4.68287374  6.04682107  5.24431036  1.07680797  5.8876399
   8.88841481  6.80915597  0.42884655 10.89154733]]


**49. How to find the most frequent value in an array?**

In [51]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax());

3


**50. Extract all the contiguous 3x3 blocks from a random 10x10 matrix**

In [52]:
from numpy.lib import stride_tricks
Z = np.random.randint(0,5,(10,10));
n = 3;
i = 1 + (Z.shape[0] - 3)
j =  1 + (Z.shape[1] - 3)
C = stride_tricks.as_strided(Z, shape=(i,j,n,n), strides=Z.strides + Z.strides)
print(C)

[[[[0 4 4]
   [4 2 3]
   [1 3 4]]

  [[4 4 4]
   [2 3 4]
   [3 4 1]]

  [[4 4 1]
   [3 4 1]
   [4 1 1]]

  [[4 1 0]
   [4 1 3]
   [1 1 4]]

  [[1 0 2]
   [1 3 2]
   [1 4 3]]

  [[0 2 4]
   [3 2 0]
   [4 3 3]]

  [[2 4 3]
   [2 0 4]
   [3 3 2]]

  [[4 3 1]
   [0 4 1]
   [3 2 4]]]


 [[[4 2 3]
   [1 3 4]
   [0 4 4]]

  [[2 3 4]
   [3 4 1]
   [4 4 0]]

  [[3 4 1]
   [4 1 1]
   [4 0 0]]

  [[4 1 3]
   [1 1 4]
   [0 0 4]]

  [[1 3 2]
   [1 4 3]
   [0 4 0]]

  [[3 2 0]
   [4 3 3]
   [4 0 1]]

  [[2 0 4]
   [3 3 2]
   [0 1 2]]

  [[0 4 1]
   [3 2 4]
   [1 2 2]]]


 [[[1 3 4]
   [0 4 4]
   [2 3 4]]

  [[3 4 1]
   [4 4 0]
   [3 4 1]]

  [[4 1 1]
   [4 0 0]
   [4 1 4]]

  [[1 1 4]
   [0 0 4]
   [1 4 4]]

  [[1 4 3]
   [0 4 0]
   [4 4 0]]

  [[4 3 3]
   [4 0 1]
   [4 0 3]]

  [[3 3 2]
   [0 1 2]
   [0 3 2]]

  [[3 2 4]
   [1 2 2]
   [3 2 4]]]


 [[[0 4 4]
   [2 3 4]
   [0 4 2]]

  [[4 4 0]
   [3 4 1]
   [4 2 1]]

  [[4 0 0]
   [4 1 4]
   [2 1 2]]

  [[0 0 4]
   [1 4 4]
   [1 2 3]]

  [[0 4 0]
   

**51. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?**

In [53]:
z = np.ones((16,16));
k = 4;
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis = 0),
                    np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[42 29 19]
 [22 38 20]
 [17 17  3]]


**52. How to get the n largest values of an array**

In [54]:
Z = np.arange(10000);
np.random.shuffle(Z);
n=5;

#slow
print(Z[np.argsort(Z)[-n:]])

#fast
print(Z[np.argpartition(-Z,n)[:n]]);

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


**53. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements, of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).**

In [55]:
X = np.random.randn(100)
print(X)
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means,[2.5,97.5])
print(confint)

[ 0.72235785 -1.01113608 -0.31611946 -0.90185283  0.46959318  0.2626722
 -0.65370138  0.66459116 -2.20324398 -1.7910845   0.22832198  0.6564933
  1.10037428 -0.32027124  0.32958221  0.25394814  0.44392498 -1.36412453
 -0.61937417  2.45580057  1.41576059  0.86225594 -0.10254852 -2.50798557
  0.48787619  0.06614619  0.0489657  -0.90239052 -0.72171942  0.33008852
  0.21363751 -1.9883066  -0.2612461  -0.73072971 -0.81968444 -0.2391024
 -0.81294472 -0.14407908  0.48217242  0.43142165 -1.16417744  0.33102091
  0.08894173 -0.28656157 -1.29827855  0.66512476 -0.120274   -0.73376352
  0.16023882  1.82263067  0.58037852 -0.96285935  1.31573115 -0.78133124
 -0.3931046  -1.9375863  -0.25449675  0.94957053  0.31715181 -1.51183647
  1.28186197  0.18267067 -0.50228942  0.3214827   0.96388702 -1.07863554
 -1.11366621 -1.74387987  1.84530007  0.45941631  1.08135205  2.39221715
 -0.04710348  0.52956222 -0.19691726 -0.82860538  0.83689129 -0.41198179
  0.4159815  -0.21347721 -0.52230597  0.64722492  1.04